- name: Install git and related tools from distribution package
  hosts: all
  become: true
  vars:
    apt_packages:
    - git
    - gitk

  tasks:
  - name: Update apt cache
    apt:
      update_cache: yes

  - name: Install the apt packages
    apt:
      name: "{{ apt_packages }}"
      state: present
