- name: Install i3
  hosts: all
  become: true

  tasks:
  - name: Get distribution name
    command: lsb_release -is
    register: distro_name

  - name: Get distribution code name
    command: lsb_release -cs
    register: distro_codename

  - name: Add deb-src to sources.list for Ubuntu
    lineinfile:
      path: /etc/apt/sources.list
      line: "deb-src http://archive.ubuntu.com/ubuntu {{ distro_codename.stdout }} main universe"
      state: present
    tags: add-deb-src-ubuntu
    when: distro_name.stdout == "Ubuntu"

  - name: Add deb-src to sources.list for Debian
    lineinfile:
      path: /etc/apt/sources.list
      line: "deb-src http://deb.debian.org/debian {{ distro_codename.stdout }} main"
      state: present
    tags: add-deb-src-debian
    when: distro_name.stdout == "Debian"

  - name: Install i3 dependencies by using apt-get build-dep i3
    apt:
      name: i3
      state: build-dep

  - name: Update apt cache
    apt:
      update_cache: yes

  - name: Clone, build and install i3
    shell: |
      git clone https://github.com/i3/i3.git /tmp/i3
      cd /tmp/i3
      mkdir -p build
      cd build
      meson ..
      ninja
      ninja install
    args:
      executable: /bin/bash
    tags: clone-build-install-i3

  - name: Remove i3 directory
    file:
      path: /tmp/i3
      state: absent
