- name: Install essential tools
  hosts: all
  gather_facts: true
  become: true
  vars:
    apt_packages:
    - git
    - gitk
    - fzf
    - meld
    - bat
    - exa
    - ripgrep
    - tmux
    - curl
    - feh

  tasks:
  - name: Update apt cache
    apt:
      update_cache: yes

  - name: Install apt tools
    apt:
      name: "{{ apt_packages }}"
      state: present
