---
- name: Copy SSH keys to remote machine
  hosts: all
  become_user: "{{ ansible_user }}"
  tasks:
    # Ensure that the .ssh directory exists
    - name: Create .ssh directory
      file:
        path: "/home/{{ ansible_user }}/.ssh"
        state: directory
        mode: 0700

    - name: Copy id_rsa private key
      copy:
        src: ~/.ssh/id_rsa
        dest: "/home/{{ ansible_user }}/.ssh/id_rsa"
        mode: 0600

    - name: Copy id_rsa.pub public key
      copy:
        src: ~/.ssh/id_rsa.pub
        dest: "/home/{{ ansible_user }}/.ssh/id_rsa.pub"
        mode: 0644

    - name: Add ssh key to bashrc
      lineinfile:
        path: "/home/{{ ansible_user }}/.bashrc"
        line: |
          if [ -z "$SSH_AUTH_SOCK" ] ; then
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/id_rsa
          fi
      args:
        insertafter: EOF

    - name: Copy .gitconfig
      copy:
        src: ~/.gitconfig
        dest: "/home/{{ ansible_user }}/"
        mode: 0644
