---
- name: Install zoxide
  hosts: all
  become: false
  become_user: "{{ ansible_user }}"

  tasks:
    - name: Download install.sh script
      get_url:
        url: https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh
        dest: $HOME/tmp/install.sh

    - name: Execute install.sh script
      command: bash $HOME/tmp/install.sh