---
- name: Install essential tools
  hosts: all
  gather_facts: true
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install apt tools
      apt:
        name:
          - git
          - gitk
          - fzf
          - neovim
          - meld
        state: present

    - name: Install lazygit
      shell: |
        LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep -Po '"tag_name": "v\K[^"]*')
        curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz"
        tar xf lazygit.tar.gz lazygit
        sudo install lazygit /usr/local/bin
      args:
        executable: /bin/bash
