- name: Copy SSH keys to remote machine
  hosts: all
  become_user: "{{ ansible_user }}"
  tasks:
    - name: Copy id_rsa private key
      copy:
        src: ~/.ssh/id_rsa
        dest: "/home/{{ ansible_user }}/.ssh/id_rsa"
        mode: 0600

    - name: Copy id_rsa.pub public key
      copy:
        src: ~/.ssh/id_rsa.pub
        dest: "/home/{{ ansible_user }}/.ssh/id_rsa.pub"
        mode: 0644

    - name: Add ssh key to bashrc
      lineinfile:
        path: "/home/{{ ansible_user }}/.bashrc"
        line: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
      args:
        insertafter: EOF
