- name: Install essential tools
  hosts: all
  gather_facts: true
  become: true
  vars:
    apt_packages:
    - git
    - gitk
    - fzf
    - meld
    - bat
    - exa
    - ripgrep
    - tmux
    - curl

  tasks:
  - name: Update apt cache
    apt:
      update_cache: yes

  - name: Install apt tools
    apt:
      name: "{{ apt_packages }}"
      state: present

  - name: Install zoxide, a better cd command for your terminal
    command: curl -sS https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | bash -s -- -y
    become_user: "{{ ansible_user }}"
    tags: install-zoxide
