- name: Install i3
  hosts: localhost
  become: true
  vars:
    i3_repo_url: "http://debian.sur5r.net/i3/"
    i3_repo_key_url: "https://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2024.03.04_all.deb"
    i3_repo_key_file: "/tmp/keyring.deb"
    i3_repo_key_sha256: "f9bb4340b5ce0ded29b7e014ee9ce788006e9bbfe31e96c09b2118ab91fca734"

  tasks:
  - name: Download i3 repository key
    get_url:
      url: "{{ i3_repo_key_url }}"
      dest: "{{ i3_repo_key_file }}"
      sha256sum: "{{ i3_repo_key_sha256 }}"
      mode: '0644'

  - name: Install i3 repository key
    apt:
      deb: "{{ i3_repo_key_file }}"
      state: present

  - name: Add i3 repository
    lineinfile:
      path: /etc/apt/sources.list.d/sur5r-i3.list
      line: "deb {{ i3_repo_url }} {{ ansible_distribution_release }} universe"
      create: yes
      state: present

  - name: Update apt cache
    apt:
      update_cache: yes

  - name: Install i3
    apt:
      name: i3
      state: present
