---
- name: Install quartus
  hosts: all
  become: true
  vars:
    quartus_intaller: QuartusLiteSetup-23.1std.0.991-linux.run
    quartus_install_dir: /opt/intelFPGA_lite/23.1

  tasks:
    - name: Copy Quartus installation folder to /tmp/
      copy:
        src: ../../../../files/intel/quartus
        dest: /tmp/
        mode: 0755

    - name: Install Quartus
      shell: |
        cd /tmp/quartus
        ./{{ quartus_intaller }} --mode unattended \
        --unattendedmodeui none \
        --installdir {{ quartus_install_dir }} \
        --accept_eula 1
      args:
        executable: /bin/bash
